-- ============================================================
-- Paulistao A1 26 - Perifericos (historico)
-- Gerado de: Planilha de controle - Paulistao Perifericos A1 26
-- 74 jogos - 37 colunas
--
-- Cria o campeonato no Portal e carrega os jogos.
-- NAO toca em Brasileirao, Paulistao Feminino, nem em nenhuma
-- tabela que ja existe. Rodar de novo NAO duplica nada.
-- ============================================================

BEGIN;

-- 1) O campeonato (nada acontece se o slug ja existir)
INSERT INTO competitions (slug, label, accent_color, accent_bg, template_key, section_kind, sort_order)
SELECT 'paulistao-a1', 'Paulistão A1 26', '#DC2626', '#1a0606', 'dynamic', 'controle', 30
WHERE NOT EXISTS (SELECT 1 FROM competitions WHERE slug = 'paulistao-a1');

-- 2) As colunas
INSERT INTO competition_columns (competition_id, key, label, type, options, width, col_group, sticky, sort_order)
SELECT c.id, v.key, v.label, v.type, v.options::jsonb, v.width, v.col_group, v.sticky, v.sort_order
FROM competitions c, (VALUES
  ('rod', 'Rod', 'text', '[]', 50, 'Jogo', true, 10),
  ('data', 'Data', 'text', '[]', 62, 'Jogo', true, 20),
  ('mandante', 'Mandante', 'text', '[]', 120, 'Jogo', true, 30),
  ('visitante', 'Visitante', 'text', '[]', 120, 'Jogo', true, 40),
  ('dia', 'Dia', 'text', '[]', 88, 'Jogo', false, 50),
  ('hora_brt', 'Hora BRT', 'text', '[]', 72, 'Jogo', false, 60),
  ('estadio', 'Estádio', 'text', '[]', 150, 'Jogo', false, 70),
  ('cidade', 'Cidade', 'text', '[]', 120, 'Jogo', false, 80),
  ('padrao', 'Padrão', 'text', '[]', 62, 'Jogo', false, 90),
  ('detentor', 'Detentor', 'text', '[]', 150, 'Jogo', false, 100),
  ('credenciamento', 'Credenciamento', 'select', '["Enviado","Parcial","Pendente","Alteração"]', 115, 'Credenciamento', false, 110),
  ('drone', 'Drone', 'select', '["Sim","Não","Aguardando OK"]', 78, 'Aéreo', false, 120),
  ('fornecedor_drone', 'Forn. Drone', 'text', '[]', 120, 'Aéreo', false, 130),
  ('minidrone', 'MiniDrone', 'select', '["Sim","Não","Aguardando OK"]', 88, 'Aéreo', false, 140),
  ('fornecedor_minidrone', 'Forn. MiniDrone', 'text', '[]', 125, 'Aéreo', false, 150),
  ('dslr', 'DSLR', 'select', '["Sim","Não","Aguardando OK"]', 72, 'Câmeras', false, 160),
  ('fornecedor_dslr', 'Forn. DSLR', 'text', '[]', 120, 'Câmeras', false, 170),
  ('qtde_dslr', 'Qtde DSLR', 'text', '[]', 72, 'Câmeras', false, 180),
  ('golcam', 'GolCam', 'select', '["Sim","Não","Aguardando OK"]', 78, 'Câmeras', false, 190),
  ('fornecedor_golcam', 'Forn. GolCam', 'text', '[]', 120, 'Câmeras', false, 200),
  ('earcam', 'EarCam', 'select', '["Sim","Não","Aguardando OK"]', 78, 'Câmeras', false, 210),
  ('fornecedor_earcam', 'Forn. EarCam', 'text', '[]', 120, 'Câmeras', false, 220),
  ('ultracam', 'UltraCam', 'select', '["Sim","Não","Aguardando OK"]', 85, 'Câmeras', false, 230),
  ('fornecedor_ultracam', 'Forn. UltraCam', 'text', '[]', 125, 'Câmeras', false, 240),
  ('grua', 'Grua', 'select', '["Sim","Não","Aguardando OK"]', 72, 'Movimento', false, 250),
  ('fornecedor_grua', 'Forn. Grua', 'text', '[]', 120, 'Movimento', false, 260),
  ('carrinho', 'Carrinho', 'select', '["Sim","Não","Aguardando OK"]', 82, 'Movimento', false, 270),
  ('fornecedor_carrinho', 'Forn. Carrinho', 'text', '[]', 125, 'Movimento', false, 280),
  ('klover', 'Klover', 'select', '["Sim","Não","Aguardando OK"]', 72, 'Áudio', false, 290),
  ('fornecedor_klover', 'Forn. Klover', 'text', '[]', 120, 'Áudio', false, 300),
  ('micros_especiais', 'Micros Especiais', 'select', '["Sim","Não","Aguardando OK"]', 110, 'Áudio', false, 310),
  ('fornecedor_micros', 'Forn. Micros', 'text', '[]', 120, 'Áudio', false, 320),
  ('internet_led', 'Internet LED', 'select', '["Sim","Não","Aguardando OK"]', 98, 'Extras', false, 330),
  ('fornecedor_internet_led', 'Forn. Internet LED', 'text', '[]', 135, 'Extras', false, 340),
  ('assinatura_craque', 'Assinatura Craque', 'select', '["Sim","Não","Aguardando OK"]', 120, 'Extras', false, 350),
  ('cadeirao', 'Cadeirão', 'select', '["Sim","Não","Aguardando OK"]', 82, 'Extras', false, 360),
  ('fornecedor_cadeirao', 'Forn. Cadeirão', 'text', '[]', 125, 'Extras', false, 370)
) AS v(key, label, type, options, width, col_group, sticky, sort_order)
WHERE c.slug = 'paulistao-a1'
ON CONFLICT (competition_id, key) DO NOTHING;

-- 3) Os 74 jogos (so entra se o campeonato ainda estiver vazio)
INSERT INTO competition_events (competition_id, data)
SELECT c.id, v.data::jsonb
FROM competitions c, (VALUES
  ('{"rod":"1","data":"10/01","mandante":"São Bernardo","visitante":"Capivariano","dia":"sábado","hora_brt":"15:00","estadio":"1º de Maio","cidade":"São Bernardo","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"1"}'),
  ('{"rod":"1","data":"10/01","mandante":"Santos","visitante":"Novorizontino","dia":"sábado","hora_brt":"16:00","estadio":"Vila Belmiro","cidade":"Santos","padrao":"B2","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"1","data":"10/01","mandante":"Guarani","visitante":"EC Primavera","dia":"sábado","hora_brt":"18:30","estadio":"Brinco de Ouro","cidade":"Campinas","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"EPTV","qtde_dslr":"1"}'),
  ('{"rod":"1","data":"10/01","mandante":"Portuguesa","visitante":"Palmeiras","dia":"sábado","hora_brt":"20:30","estadio":"Canindé","cidade":"São Paulo","padrao":"B2","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Sim","fornecedor_minidrone":"OneSolve","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"1","data":"11/01","mandante":"Corinthians","visitante":"Ponte Preta","dia":"domingo","hora_brt":"16:00","estadio":"Neo Quimica Arena","cidade":"São Paulo","padrao":"B2","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"1","data":"11/01","mandante":"Velo Clube","visitante":"Botafogo","dia":"domingo","hora_brt":"17:00","estadio":"Benito Agnelo Castellano","cidade":"Rio Claro","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"1","data":"11/01","mandante":"EC Noroeste","visitante":"RB Bragantino","dia":"domingo","hora_brt":"18:15","estadio":"Doutor Alfredo de Castilho","cidade":"Bauru","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"1","data":"11/01","mandante":"Mirassol","visitante":"São Paulo","dia":"domingo","hora_brt":"20:30","estadio":"Campos Maia","cidade":"Mirassol","padrao":"B2","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"D Nadai","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"D Nadai","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"2","data":"13/01","mandante":"Novorizontino","visitante":"Guarani","dia":"terça-feira","hora_brt":"19:00","estadio":"Jorge Ismael de Biasi","cidade":"Novo Horizonte","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"2","data":"13/01","mandante":"Capivariano","visitante":"Portuguesa","dia":"terça-feira","hora_brt":"21:30","estadio":"Municipal Carlos Colnaghi","cidade":"Capivari","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"2","data":"14/01","mandante":"EC Primavera","visitante":"Mirassol","dia":"quarta-feira","hora_brt":"19:00","estadio":"Ítalo Mário Limongi","cidade":"Indaiatuba","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"1"}'),
  ('{"rod":"2","data":"14/01","mandante":"Palmeiras","visitante":"Santos","dia":"quarta-feira","hora_brt":"19:30","estadio":"Arena Barueri","cidade":"São Paulo","padrao":"B1","detentor":"Todos","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Sim","fornecedor_minidrone":"OneSolve","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"3","golcam":"Sim","fornecedor_golcam":"D Nadai","earcam":"Sim","fornecedor_earcam":"OneSolve","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","micros_especiais":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim","cadeirao":"Não"}'),
  ('{"rod":"2","data":"14/01","mandante":"Ponte Preta","visitante":"Velo Clube","dia":"quarta-feira","hora_brt":"21:00","estadio":"Moisés Lucarelli","cidade":"Campinas","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"EPTV","qtde_dslr":"1"}'),
  ('{"rod":"2","data":"15/01","mandante":"Botafogo","visitante":"EC Noroeste","dia":"quinta-feira","hora_brt":"19:00","estadio":"Arena NicNet","cidade":"Ribeirão Preto","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"2","data":"15/01","mandante":"RB Bragantino","visitante":"Corinthians","dia":"quinta-feira","hora_brt":"19:30","estadio":"Cícero de Souza Marques","cidade":"Bragança Paulista","padrao":"B2","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"F21 Glauber","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"2","data":"15/01","mandante":"São Paulo","visitante":"São Bernardo","dia":"quinta-feira","hora_brt":"21:45","estadio":"Morumbi","cidade":"São Paulo","padrao":"B2","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"3","data":"17/01","mandante":"EC Primavera","visitante":"Novorizontino","dia":"sábado","hora_brt":"16:00","estadio":"Ítalo Mário Limongi","cidade":"Indaiatuba","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"1"}'),
  ('{"rod":"3","data":"17/01","mandante":"Portuguesa","visitante":"Velo Clube","dia":"sábado","hora_brt":"17:00","estadio":"Canindé","cidade":"São Paulo","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"1"}'),
  ('{"rod":"3","data":"17/01","mandante":"Capivariano","visitante":"Ponte Preta","dia":"sábado","hora_brt":"18:30","estadio":"Municipal Carlos Colnaghi","cidade":"Capivari","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"3","data":"17/01","mandante":"Palmeiras","visitante":"Mirassol","dia":"sábado","hora_brt":"20:30","estadio":"Arena Barueri","cidade":"São Paulo","padrao":"B2","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"F21 Glauber","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"3","data":"18/01","mandante":"Corinthians","visitante":"São Paulo","dia":"domingo","hora_brt":"16:00","estadio":"Neo Quimica Arena","cidade":"São Paulo","padrao":"B1","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Sim","fornecedor_minidrone":"OneSolve","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"3","golcam":"Sim","fornecedor_golcam":"D Nadai","earcam":"Sim","fornecedor_earcam":"OneSolve","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"3","data":"18/01","mandante":"São Bernardo","visitante":"EC Noroeste","dia":"domingo","hora_brt":"15:00","estadio":"1º de Maio","cidade":"São Bernardo","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"3","data":"18/01","mandante":"RB Bragantino","visitante":"Botafogo","dia":"domingo","hora_brt":"18:15","estadio":"Cícero de Souza Marques","cidade":"Bragança Paulista","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"1"}'),
  ('{"rod":"3","data":"18/01","mandante":"Guarani","visitante":"Santos","dia":"domingo","hora_brt":"20:30","estadio":"Brinco de Ouro","cidade":"Campinas","padrao":"B2","detentor":"Todos","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"F21 Glauber","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"4","data":"20/01","mandante":"Novorizontino","visitante":"Palmeiras","dia":"terça-feira","hora_brt":"20:00","estadio":"Jorge Ismael de Biasi","cidade":"Novo Horizonte","padrao":"B2","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"D Nadai","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"D Nadai","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"4","data":"21/01","mandante":"EC Noroeste","visitante":"Capivariano","dia":"quarta-feira","hora_brt":"19:00","estadio":"Doutor Alfredo de Castilho","cidade":"Bauru","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"4","data":"21/01","mandante":"São Paulo","visitante":"Portuguesa","dia":"quarta-feira","hora_brt":"19:30","estadio":"Morumbi","cidade":"São Paulo","padrao":"B2","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"F21 Glauber","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"4","data":"21/01","mandante":"Mirassol","visitante":"RB Bragantino","dia":"quarta-feira","hora_brt":"20:00","estadio":"Campos Maia","cidade":"Mirassol","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"4","data":"21/01","mandante":"Ponte Preta","visitante":"São Bernardo","dia":"quarta-feira","hora_brt":"21:30","estadio":"Moisés Lucarelli","cidade":"Campinas","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"EPTV","qtde_dslr":"1"}'),
  ('{"rod":"4","data":"22/01","mandante":"Santos","visitante":"Corinthians","dia":"quinta-feira","hora_brt":"19:30","estadio":"Vila Belmiro","cidade":"Santos","padrao":"B1","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Sim","fornecedor_minidrone":"OneSolve","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"3","golcam":"Sim","fornecedor_golcam":"D Nadai","earcam":"Sim","fornecedor_earcam":"OneSolve","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"4","data":"22/01","mandante":"Botafogo","visitante":"EC Primavera","dia":"quinta-feira","hora_brt":"20:00","estadio":"Arena NicNet","cidade":"Ribeirão Preto","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"4","data":"22/01","mandante":"Velo Clube","visitante":"Guarani","dia":"quinta-feira","hora_brt":"21:30","estadio":"Benito Agnelo Castellano","cidade":"Rio Claro","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"5","data":"24/01","mandante":"São Bernardo","visitante":"Mirassol","dia":"sábado","hora_brt":"15:00","estadio":"1º de Maio","cidade":"São Bernardo","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"1"}'),
  ('{"rod":"5","data":"24/01","mandante":"Ponte Preta","visitante":"EC Noroeste","dia":"sábado","hora_brt":"17:00","estadio":"Moisés Lucarelli","cidade":"Campinas","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"EPTV","qtde_dslr":"1"}'),
  ('{"rod":"5","data":"24/01","mandante":"Palmeiras","visitante":"São Paulo","dia":"sábado","hora_brt":"18:30","estadio":"Arena Barueri","cidade":"Barueri","padrao":"B1","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"3","golcam":"Sim","fornecedor_golcam":"D Nadai","earcam":"Sim","fornecedor_earcam":"OneSolve","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"5","data":"25/01","mandante":"Santos","visitante":"RB Bragantino","dia":"domingo","hora_brt":"16:00","estadio":"Neo Quimica Arena","cidade":"São Paulo","padrao":"B2","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"F21 Glauber","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"5","data":"25/01","mandante":"Capivariano","visitante":"EC Primavera","dia":"domingo","hora_brt":"17:00","estadio":"Municipal Carlos Colnaghi","cidade":"Capivari","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"5","data":"25/01","mandante":"Novorizontino","visitante":"Botafogo","dia":"domingo","hora_brt":"18:30","estadio":"Jorge Ismael de Biasi","cidade":"Novo Horizonte","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"5","data":"25/01","mandante":"Velo Clube","visitante":"Corinthians","dia":"domingo","hora_brt":"20:30","estadio":"Benito Agnelo Castellano","cidade":"Rio Claro","padrao":"B2","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"D Nadai","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"D Nadai","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Não"}'),
  ('{"rod":"5","data":"26/01","mandante":"Portuguesa","visitante":"Guarani","dia":"segunda-feira","hora_brt":"20:00","estadio":"Canindé","cidade":"São Paulo","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"1"}'),
  ('{"rod":"6","data":"31/01","mandante":"Guarani","visitante":"Ponte Preta","dia":"sábado","hora_brt":"16:00","estadio":"Brinco de Ouro","cidade":"Campinas","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"EPTV","qtde_dslr":"1","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"6","data":"31/01","mandante":"São Paulo","visitante":"Santos","dia":"sábado","hora_brt":"20:30","estadio":"Morumbi","cidade":"São Paulo","padrao":"B1","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"F21 Glauber","minidrone":"Sim","fornecedor_minidrone":"OneSolve","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"3","golcam":"Sim","fornecedor_golcam":"D Nadai","earcam":"Sim","fornecedor_earcam":"OneSolve","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"6","data":"31/01","mandante":"EC Primavera","visitante":"Portuguesa","dia":"sábado","hora_brt":"20:30","estadio":"Ítalo Mário Limongi","cidade":"Indaiatuba","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"1"}'),
  ('{"rod":"6","data":"01/02","mandante":"RB Bragantino","visitante":"São Bernardo","dia":"domingo","hora_brt":"18:15","estadio":"Cícero de Souza Marques","cidade":"Bragança Paulista","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"6","data":"01/02","mandante":"Mirassol","visitante":"Novorizontino","dia":"domingo","hora_brt":"18:30","estadio":"Campos Maia","cidade":"Mirassol","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"6","data":"01/02","mandante":"EC Noroeste","visitante":"Velo Clube","dia":"domingo","hora_brt":"19:30","estadio":"Doutor Alfredo de Castilho","cidade":"Bauru","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"6","data":"01/02","mandante":"Botafogo","visitante":"Palmeiras","dia":"domingo","hora_brt":"20:30","estadio":"Arena NicNet","cidade":"Ribeirão Preto","padrao":"B2","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"D Nadai","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"D Nadai","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"6","data":"05/02","mandante":"Corinthians","visitante":"Capivariano","dia":"quinta-feira","hora_brt":"20:30","estadio":"Neo Quimica Arena","cidade":"São Paulo","padrao":"B2","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"7","data":"07/02","mandante":"Portuguesa","visitante":"Ponte Preta","dia":"sábado","hora_brt":"16:00","estadio":"Canindé","cidade":"São Paulo","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"1","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"7","data":"07/02","mandante":"Guarani","visitante":"Botafogo","dia":"sábado","hora_brt":"18:30","estadio":"Brinco de Ouro","cidade":"Campinas","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"EPTV","qtde_dslr":"1"}'),
  ('{"rod":"7","data":"07/02","mandante":"Novorizontino","visitante":"São Bernardo","dia":"sábado","hora_brt":"18:30","estadio":"Jorge Ismael de Biasi","cidade":"Novo Horizonte","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"7","data":"07/02","mandante":"São Paulo","visitante":"EC Primavera","dia":"sábado","hora_brt":"20:30","estadio":"Morumbi","cidade":"São Paulo","padrao":"B2","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"F21 Glauber","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"7","data":"08/02","mandante":"EC Noroeste","visitante":"Santos","dia":"domingo","hora_brt":"16:00","estadio":"Doutor Alfredo de Castilho","cidade":"Bauru","padrao":"B2","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"D Nadai","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"D Nadai","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"7","data":"08/02","mandante":"Velo Clube","visitante":"RB Bragantino","dia":"domingo","hora_brt":"18:30","estadio":"Benito Agnelo Castellano","cidade":"Rio Claro","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"7","data":"08/02","mandante":"Capivariano","visitante":"Mirassol","dia":"domingo","hora_brt":"18:30","estadio":"Municipal Carlos Colnaghi","cidade":"Capivari","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"7","data":"08/02","mandante":"Corinthians","visitante":"Palmeiras","dia":"domingo","hora_brt":"20:30","estadio":"Neo Quimica Arena","cidade":"São Paulo","padrao":"B1","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Sim","fornecedor_minidrone":"OneSolve","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"3","golcam":"Sim","fornecedor_golcam":"D Nadai","earcam":"Sim","fornecedor_earcam":"OneSolve","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"8","data":"15/02","mandante":"São Bernardo","visitante":"Corinthians","dia":"domingo","hora_brt":"20:30","estadio":"1º de Maio","cidade":"São Bernardo","padrao":"B2","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"D Nadai","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"8","data":"15/02","mandante":"Botafogo","visitante":"Capivariano","dia":"domingo","hora_brt":"20:30","estadio":"Arena NicNet","cidade":"Ribeirão Preto","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"8","data":"15/02","mandante":"Ponte Preta","visitante":"São Paulo","dia":"domingo","hora_brt":"20:30","estadio":"Moisés Lucarelli","cidade":"Campinas","padrao":"B2","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"F21 Glauber","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"8","data":"15/02","mandante":"RB Bragantino","visitante":"Novorizontino","dia":"domingo","hora_brt":"20:30","estadio":"Cícero de Souza Marques","cidade":"Bragança Paulista","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"8","data":"15/02","mandante":"Santos","visitante":"Velo Clube","dia":"domingo","hora_brt":"20:30","estadio":"Vila Belmiro","cidade":"Santos","padrao":"B2","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"8","data":"15/02","mandante":"EC Primavera","visitante":"EC Noroeste","dia":"domingo","hora_brt":"20:30","estadio":"Ítalo Mário Limongi","cidade":"Indaiatuba","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"1"}'),
  ('{"rod":"8","data":"15/02","mandante":"Mirassol","visitante":"Portuguesa","dia":"domingo","hora_brt":"20:30","estadio":"Campos Maia","cidade":"Mirassol","padrao":"B3","detentor":"HBO MAX","credenciamento":"Enviado","drone":"Não","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"1"}'),
  ('{"rod":"8","data":"15/02","mandante":"Palmeiras","visitante":"Guarani","dia":"domingo","hora_brt":"20:30","estadio":"Arena Barueri","cidade":"Barueri","padrao":"B2","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","grua":"Sim","fornecedor_grua":"D Nadai","internet_led":"Sim","fornecedor_internet_led":"RMDigital"}'),
  ('{"rod":"QF","data":"21/02","mandante":"RB Bragantino","visitante":"São Paulo","dia":"sábado","hora_brt":"18:30","estadio":"Cícero de Souza Marques","cidade":"Bragança Paulista","padrao":"B2 +","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Sim","fornecedor_minidrone":"OneSolve","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"3","golcam":"Não","earcam":"Sim","fornecedor_earcam":"OneSolve","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"QF","data":"21/02","mandante":"Palmeiras","visitante":"Capivariano","dia":"sábado","hora_brt":"20:30","estadio":"Arena Barueri","cidade":"Barueri","padrao":"B2 +","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"D Nadai","minidrone":"Aguardando OK","fornecedor_minidrone":"D Nadai","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"3","golcam":"Aguardando OK","fornecedor_golcam":"D Nadai","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"QF","data":"22/02","mandante":"Novorizontino","visitante":"Santos","dia":"domingo","hora_brt":"16:00","estadio":"Jorge Ismael de Biasi","cidade":"Novo Horizonte","padrao":"B2 +","detentor":"HBO/TNT","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"SALVFilms","minidrone":"Sim","fornecedor_minidrone":"SALVFilms","dslr":"Sim","fornecedor_dslr":"SALVFilms","qtde_dslr":"3","golcam":"Não","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"QF","data":"22/02","mandante":"Portuguesa","visitante":"Corinthians","dia":"domingo","hora_brt":"20:30","estadio":"Canindé","cidade":"São Paulo","padrao":"B2 +","detentor":"YTCazeTV/Record/HBO","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Sim","fornecedor_minidrone":"OneSolve","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"3","golcam":"Não","earcam":"Sim","fornecedor_earcam":"OneSolve","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"SF","data":"28/02","mandante":"Novorizontino","visitante":"Corinthians","dia":"sábado","hora_brt":"20:30","estadio":"Jorge Ismael de Biasi","cidade":"Novo Horizonte","padrao":"B1","detentor":"Todos","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Sim","fornecedor_minidrone":"OneSolve","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"3","golcam":"Sim","fornecedor_golcam":"D Nadai","earcam":"Sim","fornecedor_earcam":"OneSolve","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"SF","data":"01/03","mandante":"Palmeiras","visitante":"São Paulo","dia":"domingo","hora_brt":"20:30","estadio":"Arena Barueri","cidade":"Barueri","padrao":"B1","detentor":"Todos","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"3","golcam":"Sim","fornecedor_golcam":"D Nadai","earcam":"Sim","fornecedor_earcam":"OneSolve","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Não","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"FA","data":"04/03","mandante":"Palmeiras","visitante":"Novorizontino","dia":"quarta-feira","hora_brt":"20:00","estadio":"Arena Barueri","cidade":"Barueri","padrao":"B1","detentor":"Todos","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Não","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","golcam":"Sim","fornecedor_golcam":"D Nadai","earcam":"Sim","fornecedor_earcam":"OneSolve","ultracam":"Não","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Sim","fornecedor_carrinho":"OneSolve","klover":"Sim","fornecedor_klover":"Lineup","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"FB","data":"04/03","mandante":"Palmeiras","visitante":"Novorizontino","dia":"quarta-feira","hora_brt":"20:00","estadio":"Arena Barueri","cidade":"Barueri","padrao":"FeedB","detentor":"Todos","credenciamento":"Enviado","drone":"Sim","fornecedor_drone":"OneSolve","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","ultracam":"Sim","fornecedor_ultracam":"D Nadai"}'),
  ('{"rod":"F","data":"08/03","mandante":"Novorizontino","visitante":"Palmeiras","dia":"domingo","hora_brt":"20:30","estadio":"Jorge Ismael de Biasi","cidade":"Novo Horizonte","padrao":"B1","detentor":"Todos","credenciamento":"Parcial","drone":"Sim","fornecedor_drone":"OneSolve","minidrone":"Sim","fornecedor_minidrone":"OneSolve","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2","golcam":"Sim","fornecedor_golcam":"D Nadai","earcam":"Sim","fornecedor_earcam":"OneSolve","ultracam":"Sim","fornecedor_ultracam":"D Nadai","grua":"Sim","fornecedor_grua":"D Nadai","carrinho":"Sim","fornecedor_carrinho":"OneSolve","klover":"Sim","fornecedor_klover":"Lineup","internet_led":"Sim","fornecedor_internet_led":"RMDigital","assinatura_craque":"Sim"}'),
  ('{"rod":"FB","data":"08/03","mandante":"Novorizontino","visitante":"Palmeiras","dia":"domingo","hora_brt":"20:30","estadio":"Jorge Ismael de Biasi","cidade":"Novo Horizonte","padrao":"FeedB","detentor":"Todos","credenciamento":"Parcial","drone":"Sim","fornecedor_drone":"OneSolve","dslr":"Sim","fornecedor_dslr":"RMDigital","qtde_dslr":"2"}')
) AS v(data)
WHERE c.slug = 'paulistao-a1'
  AND NOT EXISTS (SELECT 1 FROM competition_events e WHERE e.competition_id = c.id);

COMMIT;

-- Conferencia: deve mostrar 74 jogos e 37 colunas
SELECT c.label,
       (SELECT count(*) FROM competition_events e WHERE e.competition_id = c.id) AS jogos,
       (SELECT count(*) FROM competition_columns k WHERE k.competition_id = c.id) AS colunas
FROM competitions c WHERE c.slug = 'paulistao-a1';